
const cuisineArr = [
  { name: 'American Chinese', image: 'AmericanChinese.jpg' },
  { name: 'Breakfast', image: 'Breakfast.jpg' },
  { name: 'Burgers', image: 'Burgers.jpg' },
  { name: 'Burritos', image: 'Burritos.jpg' },
  { name: 'Cheese Platter', image: 'CheesePlatter.jpg' },
  { name: 'Diner', image: 'Diner.jpg' },
  { name: 'Easy Eating', image: 'EasyEating.jpg' },
  { name: 'Fast Food', image: 'FastFood.jpg' },
  { name: 'German', image: 'German.jpg' },
  { name: 'Greek', image: 'Greek.jpeg' },
  { name: 'Grilled Cheese', image: 'GrilledCheese.jpg' },
  { name: 'Hoagies', image: 'Hoagies.jpg' },
  { name: 'Home Cooked Diner', image: 'HomeCookedDiner.jpg' },
  { name: 'Indian', image: 'Indian.jpg' },
  { name: 'Italian', image: 'Italian.jpg' },
  { name: 'Korean', image: 'Korean.jpg' },
  { name: 'Mac And Cheese', image: 'MacAndCheese.jpg' },
  { name: 'Mexican', image: 'Mexican.jpg' },
  { name: 'Middle Eastern', image: 'MiddleEastern.jpg' },
  { name: 'Pancakes', image: 'Pancakes.jpg' },
  { name: 'Pizza', image: 'Pizza.jpg' },
  { name: 'Ramen', image: 'Ramen.jpg' },
  { name: 'Seafood', image: 'Seafood.jpeg' },
  { name: 'Sushi', image: 'Sushi.jpg' },
  { name: 'Thai', image: 'Thai.jpg' },
  { name: 'Traditional Chinese', image: 'TraditionalChinese.jpg' },
  { name: 'Vietnamese', image: 'Vietnamese.jpg' },
];

export default cuisineArr;
