export { default as Apple } from './Apple';
export { default as Boxing } from './Boxing';
export { default as Brackets } from './Brackets';
export { default as Dislike } from './Dislike';
export { default as Fire } from './Fire';
export { default as Like } from './Like';
export { default as Orange } from './Orange';
export { default as Robot } from './Robot';
export { default as Winner } from './Winner';
